site_name: Avalony的笔记目录
site_description: avalony的学习笔记
theme: 
  name: 'material'
  palette:
    primary: 'Teal'
    accent: 'Red'
  language: 'zh'
  logo:
    icon: 'accessibility'
  extra:
    search:
      language: 'en, zh'
      tokenizer: '[\s\-\.]+'  
pages:
  - 概览: 'index.md'
  - 算法学习:
    - 记录: 'algorithm/record.md'
  - Java基础: 
    - 综合: 'java/base/java_base.md'
    - 锁: 'java/base/lock.md'
    - 线程池: 'java/base/threadpool.md'
    - 线程池扩展: 'java/base/threadpoolextensional.md'
    - 锁优化: 'java/base/lockoptimal.md'
    - 本地线程: 'java/base/threadlocal.md'
    - 无锁: 'java/base/cas.md'
  - Java进阶:
    - Spring: 
      - 综合: 'java/spring/spring.md'
      - SpringMvc: 'java/spring/springmvc.md'
    - Spring-boot: 
      - 综合: 'java/spring/boot/comprehensive.md'
      - 静态资源的问题: 'java/spring/boot/static-content.md'
    - Spring-cloud: 
      - 综合: 'java/spring/cloud/comprehensive.md' 
      - eureka: 'java/spring/cloud/eureka.md'
      - zuul: 'java/spring/cloud/zuul.md'
      - ribbon: 'java/spring/cloud/ribbon.md'
      - feign: 'java/spring/cloud/feign.md'
      - hystrix: 'java/spring/cloud/hystrix.md'
  - 数据库笔记: 
    - mysql: 
      - 基础: 'database/mysql/base.md'
  - 各类链接:
    - 数据结构: 'links/data_structure.md'
    - 数据库: 'links/database.md'
    - 够浪: 'links/golang.md'
    - Java框架: 'links/java_frame.md'
    - Java基础: 'links/java.md'
    - 中间件: 'links/middleware.md'
    - 开源项目: 'links/open_source_project.md'
    - PHP: "links/php.md"
    - Python: 'links/python.md'
    - Web端: 'links/web.md'
    - 其他: 'links/other.md'
  - 构建工具:
    - maven拾遗: 'java/tools/maven.md'
  - 前端:
    - react: 'web/react.md'
    - es恶补: 'web/es.md'
